apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
      app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.99.2
  ports:
    - protocol: TCP
      name: grafana
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000