apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.2
  ports:
    - name: ftps-1
      port: 21
      targetPort: 21
      protocol: TCP
    - name: ftps-2
      port: 21000
      targetPort: 21000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
 selector:
  matchLabels:
   app: ftps
 template:
  metadata:
   labels:
    app: ftps
  spec:
   containers:
   - name: ftps
     image: ftps_image
     imagePullPolicy: Never
     ports:
     - containerPort: 21
     - containerPort: 21000