apiVersion: v1
kind: Service
metadata:
  name: ftp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftp
  type: LoadBalancer
  loadBalancerIP: 192.168.99.2
  ports:
    - name: ftp-1
      port: 21
      targetPort: 21
      protocol: TCP
    - name: ftp-2
      port: 21000
      targetPort: 21000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-deploy
  labels:
    app: ftp
spec:
 selector:
  matchLabels:
   app: ftp
 template:
  metadata:
   labels:
    app: ftp
  spec:
   containers:
   - name: ftp
     image: ftp_image
     imagePullPolicy: Never
     ports:
     - containerPort: 21
     - containerPort: 21000